### ISSUE TITLE
Usage docs

### ISSUE THREAD

**Issue by wcjr** [ghostbar/angular-zxcvbn#11]
I spent a bunch of time trying to realize why my form was getting invalidated and finally realized it was because I was sending in the extras.  I had the impression from the docs that min-score required the form but now I realize that's not true.  It might help others avoid the same problem if the idea of the dictionary and the idea of min-score be more independent of one another.  I would prefer to see the code sample in the Form Validation section not reference the extras at all.  A note could certainly be made somewhere that these attributes can be used together if min-score and dictionary checking are both required.  Thanks for considering a clarification there.

I admit I didn't fully understand the extras when I first read it and didn't think much about it until I had to start chasing down my bug...maybe others will pay more attention.

**Comment by jamesclark92** [comment]
What do you mean by 'dictionary'?

**Comment by wcjr** [comment]
zxExtras

**Comment by jamesclark92** [comment]
Okay I'll update the readme

**Comment by wcjr** [comment]
Thanks, I appreciate it and hope it will help others avoid my same pitfall.
