### ISSUE TITLE
Evaluate integration of Saucelabs in order to test cross-browser compatibility on commit 

### ISSUE THREAD

**Issue by evilaliv3** [ghostbar/angular-zxcvbn#12]
It would be valuable to integrate with Saucelabs in order totest cross-browser compatibility on commit.

As the library is using karma as testing framework my suggestion is to start implemeting them using [karma-sauce-launcher](https://github.com/karma-runner/karma-sauce-launcher).

This way it will be possiblle to automatically execute all the unit test on the selection of browsers targetted by the library (all) and know proactively where it is not working.

E.g.: https://github.com/globaleaks/GlobaLeaks
![screenshot from 2016-03-14 20 36 40](https://cloud.githubusercontent.com/assets/217034/13757421/9a540b7e-ea24-11e5-8632-58bef9195fa2.png)

It would be also nice to start tracking the code quality of the project using for example [CodeClimate](https://codeclimate.com/) and tracking also the code coverage by means of [Coveralls](https://coveralls.io/) + [karma-coveralls](https://github.com/caitp/karma-coveralls)

**Comment by ghostbar** [comment]
Indeed @evilaliv3; that would be great, sadly I have no time right now for these but would gladly merge a PR that does this.

Thanks for the suggestion!

**Comment by evilaliv3** [comment]
okay!

i'm about to make my pull with the following changes:
- saucelabs+codeclimate integration + coverage tracking
- update of all dependencies to latest versions
- replacement of gulp with grunt as it benefits of more packages in relation to this topic.

\cc jamesclark92

**Comment by jamesclark92** [comment]
@evilaliv3 What libraries does grunt have that gulp doesn't? I personally prefer gulp as I find it easier to setup

**Comment by evilaliv3** [comment]
You are right @jamesclark92 

i've quite finished implementing it all in gulp ;)

**Comment by ghostbar** [comment]
Fixed on 94ec9a6c6d4b9f7f5ab140e6064a9f6ebc1e3e7b

**Comment by evilaliv3** [comment]
great!

@ghostbar i noticed that i put a wrong url in the readme;

https://travis-ci.org/ghostbar/angular-zxcvbn.js should be replaced with https://travis-ci.org/ghostbar/angular-zxcvbn

**Comment by ghostbar** [comment]
I was just seeing that :) Fixing it right now ;-)

**Comment by evilaliv3** [comment]
great!

i do not know why the build is failing for you. have you changed something while merging?

https://travis-ci.org/ghostbar/angular-zxcvbn/jobs/116268281

**Comment by ghostbar** [comment]
Yes, and just fixed it too on 8b7e69a763dc31bba971740cac2a60c4ecdc0e11

**Comment by evilaliv3** [comment]
ehehe k

the last few errors i did:
[![Saucelabs Test Status](https://saucelabs.com/browser-matrix/evilaliv3-zxcvbn.svg)](https://saucelabs.com/u/evilaliv3-zxcvbn) replace 'evilaliv3' with 'angular' in both this links.

in addition add a newline on the Readme.md where i added myself as contributor (if you like to keep me ;))

**Comment by ghostbar** [comment]
Done and done ;-)
