### ISSUE TITLE
upgrade to zxcvbn 4.3.0

### ISSUE THREAD

**Issue by wcjr** [ghostbar/angular-zxcvbn#18]
@ghostbar , do you mind an upgrade to zxcvbn 4.3.0?  Here's the [diff](https://github.com/dropbox/zxcvbn/compare/4.2.0...4.3.0).  Thanks!

**Comment by evilaliv3** [comment]
thumbs up! :)

**Comment by evilaliv3** [comment]
zxvbn has been bumped to 4.4.0 including mixed bugfixing: https://github.com/dropbox/zxcvbn/commits/master

**Comment by wcjr** [comment]
Awesome, thank you!

**Comment by evilaliv3** [comment]
ah no @wcjr you have misunderstood.

it'szxcvb that have updated, not angular-zxcvbn :)

**Comment by wcjr** [comment]
oops, sorry about that, reopening.
