### ISSUE TITLE
Cannot install the latest version via npm

### ISSUE THREAD

**Issue by Ins87** [ghostbar/angular-zxcvbn#22]
I tried to install 3.2.2 with npm but it says it's not a valid version, and the latest version is 3.1.1 as you can see here:
https://www.npmjs.com/package/angular-zxcvbn

maybe you forgot to publish it?

**Comment by ghostbar** [comment]
I'm so sorry. I did forgot to publish it.

**Comment by Ins87** [comment]
thanks
