### ISSUE TITLE
upgrade to zxcvbn 4.3.1

### ISSUE THREAD

**Issue by evilaliv3** [ghostbar/angular-zxcvbn#23]
zxcvbn updated to 4.3.1 with mixed changes that does not break any API.

@ghostbar , do you mind an upgrade to that? Here's the [diff](https://github.com/dropbox/zxcvbn/commits/master). Thanks!

probably the adoption of the semver caret versions would allow to avoid reissuing the package when minor versions are released?

**Comment by evilaliv3** [comment]
@ghostbar i miss you :)

**Comment by ghostbar** [comment]
I'll do it tonight. Promise. Sorry!

**Comment by ghostbar** [comment]
So we had already upgraded to 4.4.1 (c8c9edd1d5308a03145aae07f49dcd26bd32b60e) and the samever caret is on. Still on 4.4.x on zxcvbn.

Looks like we are good and this should be closed?

**Comment by evilaliv3** [comment]
Ah i missed it, i was thinking that the release whas still to happen but in the real you are not keeping a changelog.

sorry for this. yes this can be closed!
