### ISSUE TITLE
Supporting controllerAs and bindToController usage

### ISSUE THREAD

**Issue by wcjr** [ghostbar/angular-zxcvbn#9]
I noticed the zxcvbn object is getting directly attached to $scope.  I've been following the pattern of the controllerAs and bindToController using the name 'vm' so everything in scope is available as vm.whatever.  I can't do that with zxcvbn and was hoping you might be able to tweak the code in a way that would allow it?  I'm not exactly sure what all would be involved but wanted to pose the request in case it was desirable for others and not too impactful to the existing code.

Thanks for the consideration,
Billy

**Comment by ghostbar** [comment]
@jamesclark92 any idea on this?

**Comment by jamesclark92** [comment]
I'll look into this

**Comment by wcjr** [comment]
Thanks for checking on it.

**Comment by m0t0r** [comment]
+1
I have the same case, I use **controllerAs** and cannot update to 3.x because it requires value on $scope.

**Comment by jamesclark92** [comment]
*Update:* I am in the process of re-writing this to allow for controller as syntax.
*Cheeky:* I believe injecting $scope should make it work

**Comment by jamesclark92** [comment]
@m0t0r @m0t0r I have re-written the attribute to be suitable for `controller as` syntax. I believe the element version of the directive was already compatible.

**Comment by m0t0r** [comment]
@jamesclark92 thank you so much, I'll check it.

**Comment by jamesclark92** [comment]
You may need to just download the source from the dist folder as I'm not sure if ghostbar has updated bower yet

**Comment by jamesclark92** [comment]
Okay  its already been done by me

**Comment by wcjr** [comment]
Thanks a bunch guys!  I'll pull this in and let you know if it caused any issues.

**Comment by wcjr** [comment]
The attribute is working great but I'm not able to make the element work.  Take a look at this plunkr and notice the vm.results is not getting populated:  http://plnkr.co/edit/U6g7na?p=preview

Am I doing something wrong?

**Comment by jamesclark92** [comment]
@wcjr 3.1.1 contains the fix for this

**Comment by wcjr** [comment]
would mind updating your bower.json version to 3.1.1? Thanks.

![image](https://cloud.githubusercontent.com/assets/4412848/12677035/3cee3b5a-c664-11e5-901f-2350fd07b4b4.png)

**Comment by jamesclark92** [comment]
@wcjr whoops - done

**Comment by wcjr** [comment]
no worries, at least it wasn't the dreaded "forgot to push tags" thing that always gets me! :-)
